device:
  layer: rpi-all
  hostname: raspberry
  user1: fog

image:
  layer: image-rpios
  boot_part_size: 200%
  root_part_size: 300%
  name: rpi-fog

layer:
  user: rpi-user-credentials
  app: fogproject
  base: trixie-minbase
